Add jank client
spacebarchat/docs pull request #92
Opened 2024-09-15 20:32 UTC by MathMan05

Add jank client to the docs

2024-09-21 03:00 UTC, Puyodead1 reviewed
Some things I think should be changed

2024-09-21 03:00 UTC, Puyodead1 commented on docs/setup/clients/jank/web.md
> +If you're wanting to also develop Jank Client, you'll need to start the type script compiler in watch mode on the base dir of the project.
```suggestion
If you're wanting to also develop Jank Client, you'll need to start the typescript compiler in watch mode on the base directory of the project.
```

2024-09-21 03:07 UTC, Puyodead1 commented on docs/setup/clients/jank/web.md
> +    Jank Client defualts to opening on port 8080, if you want to change the port you'll need to change either the env variable PORT or put the port on the command you run so it'd be like node ./index
```suggestion
    Jank Client defaults to opening on port 8080, if you want to change the port you'll need to change either the env variable PORT or put the port on the command you run, ex: `node ./index.js 43`
```

2024-09-23 08:33 UTC, TheArcaneBrony requested changes
Looks good for the most part, just have some questions.

2024-09-23 08:33 UTC, TheArcaneBrony commented on docs/setup/clients/jank/web.md
> +    Jank Client defualts to opening on port 8080, if you want to change the port you'll need to change either the env variable PORT or put the port on the command you run, ex: `npm start ./index.js 4
This is a development tool. Rewrite the build instructions to compile a static web root and provide instructions to serve with nginx or similar.

2024-09-23 08:33 UTC, TheArcaneBrony commented on docs/setup/clients/jank/web.md
> +-   Pull request & done!
Is there a non-pull request flow for folks who don't use, or prefer not to use GitHub?

2024-09-23 08:33 UTC, TheArcaneBrony commented on docs/setup/clients/jank/web.md
> +-   If you have an instance you can put it on Jank Clients [instance list](https://github.com/MathMan05/JankClient/blob/main/InstanceInfo.md), if you don't it'll show up on Jank Client if it's on the
Perhaps provide a link to the official instance list?

2024-09-23 13:26 UTC, MathMan05 commented on docs/setup/clients/jank/web.md
> +-   If you have an instance you can put it on Jank Clients [instance list](https://github.com/MathMan05/JankClient/blob/main/InstanceInfo.md), if you don't it'll show up on Jank Client if it's on the
wdym

2024-09-23 13:27 UTC, MathMan05 commented on docs/setup/clients/jank/web.md
> +-   Pull request & done!
not as of now, I only have a github

2024-09-23 13:28 UTC, TheArcaneBrony commented on docs/setup/clients/jank/web.md
> +-   If you have an instance you can put it on Jank Clients [instance list](https://github.com/MathMan05/JankClient/blob/main/InstanceInfo.md), if you don't it'll show up on Jank Client if it's on the
as in, include a direct link to the official intance list instead of just saying "this thing i dont provide a link to", just use a masked link to the repo or something

2024-09-23 13:30 UTC, MathMan05 commented on docs/setup/clients/jank/web.md
> +-   If you have an instance you can put it on Jank Clients [instance list](https://github.com/MathMan05/JankClient/blob/main/InstanceInfo.md), if you don't it'll show up on Jank Client if it's on the
Oh, I need to rewrite for clarity, that's not what that means

2024-09-23 13:32 UTC, MathMan05 commented on docs/setup/clients/jank/web.md
> +-   Pull request & done!
I do have github/spacebar, though I don't know how exactly that's supposed to work, as neither are git providors

2024-09-23 13:33 UTC, TheArcaneBrony commented on docs/setup/clients/jank/web.md
> +-   If you have an instance you can put it on Jank Clients [instance list](https://github.com/MathMan05/JankClient/blob/main/InstanceInfo.md), if you don't it'll show up on Jank Client if it's on the
i meant more, the "if you don't it'll show up on Jank Client if it's on the official instance list," part

2024-09-23 13:35 UTC, TheArcaneBrony commented on docs/setup/clients/jank/web.md
> +-   Pull request & done!
sending in patches outside of git (eg. `git format-patch` -> `git am *.patch`), via any means of communication that can share one or more files :)

2024-09-23 13:37 UTC, MathMan05 commented on docs/setup/clients/jank/web.md
> +-   Pull request & done!
I mean technically that'd work, but as with the official client
![image](https://github.com/user-attachments/assets/ff6114db-47e5-4272-86a2-03b869c77913)
I don't really want to encourage that type of commit

2024-09-23 13:38 UTC, TheArcaneBrony commented on docs/setup/clients/jank/web.md
> +-   Pull request & done!
fair, i guess im probably one of few people who would prefer to just send in patch files than whatever the hell messy thing that is github fork+pr :P

2024-09-23 13:40 UTC, MathMan05 commented on docs/setup/clients/jank/web.md
> +-   If you have an instance you can put it on Jank Clients [instance list](https://github.com/MathMan05/JankClient/blob/main/InstanceInfo.md), if you don't it'll show up on Jank Client if it's on the
just saw this, I did fix it

2024-09-23 13:41 UTC, MathMan05 commented on docs/setup/clients/jank/web.md
> +    Jank Client defualts to opening on port 8080, if you want to change the port you'll need to change either the env variable PORT or put the port on the command you run, ex: `npm start ./index.js 4
I pinged you on discord so we could talk about this with most instance comunication

2024-11-02 20:27 UTC, MathMan05 commented
So uh, is there going anywhere? I was asked to do this a while back, but these docs have just been kinda dead sitting here

2024-11-02 23:16 UTC, merged